import PageSEO from "@/components/SEO"
import Link from "next/link"

export default function LandingPage({ posts }) {
	return (
		<>
			<PageSEO title="Home" description="thinking" />
			<h1>Home Page</h1>
			<p>
				Click the link below to navigate to a page generated by{' '}
				<code>next-mdx-remote</code>.
			</p>
			<ul>
				{posts.map((post) => (
					<li key={post.filePath}>
						<Link
							as={`/posts/${post.filePath.replace(/\.mdx?$/, '')}`}
							href={`/posts/[slug]`}
						>
							<a>{post.data.title}</a>
						</Link>
					</li>
				))}
			</ul>
		</>
	)
}